@startuml "Deployment Diagram"
!theme cerulean-outline
!include plantuml/sprites/common.puml
!include plantuml/sprites/orleans.puml
title "WebScheduler Deployment"

<style>
component {
        HorizontalAlignment center
}
</style>


package "WebScheduler.Server" as WebSchedulerServerPackage {

    
    component "<$t_orleans,scale=0.5,color=purple>\nOrleans Silo" as OrleansSilo #White
    
    component "Orleans Dashboard" as OrleansDashboard 
    component "Health Checks" as OrleansHealthChecks 

}


package "WebScheduler.FrontEnd" as WebSchedulerFrontEnd {

    
    component "Blazor WebAssembly" as Blazor

}

package "WebScheduler.Api" as WebSchedulerApiPackage {

    component "Health Checks" as WebApiHealthChecks 
    component "Web API" as WebApi

}
url of OrleansSilo is [[https://github.com/web-scheduler/web-scheduler/tree/main/Source/WebScheduler.Server{Goto Code}]]

    OrleansDashboard -left-> OrleansSilo

    OrleansHealthChecks -up-> OrleansSilo

    WebApi -right-> OrleansSilo

    Blazor -up-> WebApi

@enduml
