
@startuml "LogicalDeploymentDiagram"
!theme cerulean-outline
!include plantuml/sprites/orleans.puml
!include plantuml/sprites/blazor.puml

skinparam svgLinkTarget _blank

title "WebScheduler Logical Deployment"

<style>
component {
        HorizontalAlignment center
}
</style>




    frame "WebScheduler.Server" as WebSchedulerServerPackage {
    component "<$t_orleans,scale=0.85,color=purple>\nOrleans Silo" as OrleansSilo #White  

  component "Orleans Dashboard" as OrleansDashboard 
    component "Health Checks" as OrleansHealthChecks 
    OrleansDashboard -up-> OrleansSilo
    OrleansHealthChecks -up-> OrleansSilo
}
    
    frame "WebScheduler.FrontEnd.BlazorApp" as BlazorAppFrame {
            component "<$t_blazor,scale=1,color=#702af7>\nBlazor WebAssembly" as BlazorApp #White  

    }

    frame "WebScheduler.Api" as WebApiPackage {
        component "Web API Host" as WebApiHost
        component "Health Checks" as WebApiHealthChecks
        WebApiHealthChecks -up-> WebApiHost
    }

url of OrleansSilo is [[https://github.com/web-scheduler/web-scheduler/tree/main/Source/WebScheduler.Server{Goto Code}]]


    WebApiHost -left-> OrleansSilo

    BlazorApp -left-> WebApiHost

@enduml
