alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: DEPLOYMENT_LIVE
  - rule: DOMAIN_LIVE
domains:
  - domain: throw.nullreference.io
    type: PRIMARY
  - domain: www.throw.nullreference.io
    type: ALIAS
ingress:
  rules:
    - component:
        name: throw-nullreference-io
      cors:
        allow_origins:
          - exact: https://throw.nullreference.io
          - exact: https://www.throw.nullreference.io
      match:
        path:
          prefix: /
name: throw-nullreference-io
region: nyc
static_sites:
  - name: web
    source_dir: /
    build_command: corepack enable && yarn install --frozen-lockfile && yarn build
    output_dir: out
    cache_directories:
      - .next/cache
    environment_slug: node-js
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        scope: BUILD_TIME
        value: https://throw.nullreference.io
    catchall_document: 404.html

    github:
      repo: ElanHasson/throw.nullreference.io
      branch: main
      deploy_on_push: false
    index_document: index.html
output_dir: out
source_dir: /
