name: throw-nullreference-io
region: nyc
static_sites:
  - name: web
    source_dir: /
    build_command: corepack enable && yarn install --frozen-lockfile && yarn build
    output_dir: out
    environment_slug: node-js
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
    github:
      repo: ElanHasson/throw.nullreference.io
      branch: main
      deploy_on_push: true
