alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
- rule: DOMAIN_LIVE
domains:
- domain: throw.nullreference.io
  type: PRIMARY
- domain: www.throw.nullreference.io
  type: ALIAS
ingress:
  rules:
  - component:
      name: throw-nullreference-io
    cors:
      allow_origins:
      - exact: https://throw.nullreference.io
      - exact: https://www.throw.nullreference.io
    match:
      path:
        prefix: /
name: throw-nullreference-io
region: nyc
static_sites:
  - name: web
    source_dir: /
    build_command: corepack enable && yarn install --frozen-lockfile && yarn build
    output_dir: out
    environment_slug: node-js
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
    catchall_document: 404.html

    github:
      repo: ElanHasson/throw.nullreference.io
      branch: main
      deploy_on_push: true
