alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
- rule: DOMAIN_LIVE
domains:
- domain: throw.nullreference.io
  type: PRIMARY
- domain: www.throw.nullreference.io
  type: ALIAS
name: throw-nullreference-io
region: nyc
static_sites:
- build_command: npm ci && npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: ElanHasson/throw.nullreference.io
  name: throw-nullreference-io
  source_dir: /
  output_dir: out
  index_document: index.html
  catchall_document: 404.html
  cors:
    allow_origins:
      - prefix: https://throw.nullreference.io
      - prefix: https://www.throw.nullreference.io
  routes:
    - path: /
  envs:
    - key: NODE_ENV
      value: production
    - key: NEXT_PUBLIC_SITE_URL
      value: https://throw.nullreference.io
