export { AnimatedGradient } from './animated-gradient'
export { FloatingOrbs } from './floating-orbs'
export { InteractiveParticles } from './interactive-particles'
export { NeuralNetwork } from './neural-network'
export { WaveMotion } from './wave-motion'
export { GeometricGrid } from './geometric-grid'
export { CyberGrid } from './cyber-grid'
export { FractalTrees } from './fractal-trees'
export { CodeRain } from './code-rain'
export { MatrixRain } from './matrix-rain'
export { Ecosystem } from './ecosystem'
export { default as HikingTrail } from './hiking-trail'
export type { BackgroundProps, CanvasBackgroundProps } from './types'